# KNN Classification

This a classification project diabetes dataset using KNN Classifier.

### Importing Libraries

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

### Print columns,shape & size

In [ ]:
for i in df.columns:
  print(i)

Pregnancies
Glucose
BloodPressure
SkinThickness
Insulin
BMI
DiabetesPedigreeFunction
Age
Outcome


In [ ]:
print("Shape : ",df.shape)

Shape :  (768, 9)


In [ ]:
print("Size : ",df.size)

Size :  6912


In [ ]:
print("Total no. of missing values : \n")
df.isna().sum()

Total no. of missing values : 



Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

### Count of diabetic patients and non-diabetic patients:

In [ ]:
print("Count of diabetic patients : \n")
df.groupby("Outcome") ["Outcome"].count()

Count of diabetic patients : 



Outcome
0    500
1    268
Name: Outcome, dtype: int64

To separate x and y (outcome column from the others) : 

In [ ]:
x=df.iloc[:,:-1]
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [ ]:
y=df.iloc[:,-1]
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

### To convert input and ouput into array

In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

### Splitting data into training and testing data



In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)  # test_size = 0.30 => 30% testing , 70% training
y_test

array([0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0])

### **Normalization**



*   Different columns have different range of values
*   So we normalize the dataset to bring it to same range of values


There are different normalization techniques :


1.   Standard Scalar
2.   MinMax Scalar

Here, we use Standard Scalar

      Formula for Standard Scalar : 

                    z = (x-u)/s  

              where,

                    u = mean of training data

                    s = standard deviation of training data

                    




In [ ]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)
print(x_train)

[[-1.11849727 -0.269746    0.38023913 ...  0.18500025 -0.5643984
  -0.8659125 ]
 [-1.11849727  0.29830734  0.98899962 ... -0.03096743  0.77761713
  -0.06358215]
 [-1.11849727 -0.14351192 -3.47524397 ...  0.24852016  1.3230815
   1.00619165]
 ...
 [-0.81189542 -0.77468231  0.07585889 ...  0.79479135 -0.7375617
  -0.24187778]
 [ 1.02771572  1.18194588 -0.12706128 ... -0.18341521 -0.26136264
   0.29300912]
 [ 0.72111386  0.04583919  0.17731897 ...  0.22311219  0.74875658
   0.11471348]]


### Creating model

We create KNN classifier by passing the number of neighbors in KNeighborsClassifier() function.

Then, fit the model on the train set using fit() and perform prediction on the test set using predict().

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
# model fitting
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 1 0 0
 1 1 1 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0
 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1
 0 0 0 0 1 1 0 1 0 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0
 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0
 0 0 0 0 0 0 0 0 1]


In [ ]:
print(y_test)

[0 0 1 0 0 1 0 1 0 1 0 0 1 1 1 0 0 1 0 0 1 1 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0
 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0
 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1
 0 0 0 0 1 1 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 1 1 0 0 1 1 0
 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 1 0 0 1 1 0 0 0
 0 0 1 0 1 0 0 0 0]


### Predicting whether a new patient entered is diabetic or not

1 => diabetic

0 => not diabetic

In [ ]:
print(knn.predict([[4,110,70,30,5,35,0.456,50]]))

[1]


  ### Performance Evaluation
    
    => to measure the accuracy of our model

    => 100% accuracy is not possible for any models.

    There are many methods to measure performance of a model.

    1. Accuracy Score 
    2. Recall 
    3. Precision
    4. f1 square

    Confusion Matrix
        => Every method above uses confusion matix to measure the accuracy of the model.
        => There 4 technical terms to be clear while creating a confusion matrix.
              1. TP (True Positive)
                    => predicts positive truly
                    => predicted value and actual value is predicted positively
                    => predicts 1 as 1 itself.
                    => predicts 1<=>1, True<=>True
              2. TN (True Negative)
                    => predicts negative truly. 
                    => actually negative, predicted negative => true
                    => predicts 0<=>0, False<=>False
              3. FP (False Positive)
                    => actual value negative (person is diabetic),predicts positive (patiet is diabetic)
                    => predicts 0 => 1, False => True
              4. FN (False Negative)
                    => actually positive, predicts negative falsly
                    => actually diabetic, machine predicts not diabetic
                    => predicts 1 => 0, True => False
      Predicted_value : y_pred
      Actual _value : y_test

      Confusion Matrix is evaluated by : 
      |------|-----|
      |  TP  |  FP |
      |------|-----|
      |  FN  | TN  |
      |------|-----|
      
      The performance of the model is evaluated by different methods such as accuracy measure,recall,etc using confusion matrix.

      Accuracy Score Calculation : (TP + TN)/(TP + TP + FP + FN)

#### Confusion Matrix


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
conf_mat=confusion_matrix(y_pred,y_test)   # => (predicted value,actual value)
print(conf_mat)

[[123  39]
 [ 28  41]]


#### Accuracy Score

In [ ]:
score=accuracy_score(y_pred,y_test)
print(score*100,"%")

70.995670995671 %
